version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - assignment-network
  db:
    build: ./mysql
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1m2o3o4n
    volumes:
      - c:\test:/var/lib/mysql
    ports:
      - "3309:3306"  
    networks:
      - assignment-network

networks:
  assignment-network: